### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by haxck** [haxck/roll-a-ball#1]
- [x] Setting up the Game
- [x] Moving the Player
- [x] Moving the Camera
- [ ] Setting up the Play Area
- [ ] Creating Collectable Objects
- [ ] Collecting the Pick Up Objects
- [ ] Displaying the Score and Text
- [ ] Building the Game
